### ISSUE TITLE
Feature request: Option for the app connect directly to mqtt

### ISSUE THREAD

**Issue by megabyte2010** [meshtastic/Meshtastic-Android#613] opened 2023-04-05 15:59 UTC
Just an idea. Until now, we need to connect to a device by wifi, bluetooth or serial, to be able to send or receive messages. There should be an option to connect the app directly to a mqtt to be able to send messages thru internet to some remote device connected thru rf to some gateway.

**Comment by andrekir** [comment] 2023-04-06 02:40
Duplicate of #361

**Closed by andrekir** 2023-04-06 02:40 UTC
