### ISSUE TITLE
Meshtastic Android App for Android Auto functions

### ISSUE THREAD

**Issue by MALAONE1** [meshtastic/Meshtastic-Android#1354] opened 2024-10-26 17:55 UTC
### Tell us your idea.

It might be an idea to enable the Meshtastic Android app to be Android Auto compatible, so that it can communicate with Android-enabled car radios. Many other messenger apps can do this.This would be an advantage for nodes that are installed in the vehicle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment] 2024-10-27 09:33
Duplicate of #969

**Closed by andrekir** 2024-10-27 09:33 UTC
Labels: duplicate
