### ISSUE TITLE
[Feature Request]: loading bar during traceroute

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1331] opened 2024-10-20 10:19 UTC
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

show loading popup during traceroute and show if traceroute fails (e.g. after some time)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment] 2024-10-20 10:48
Duplicate of #1047

**Closed by andrekir** 2024-10-20 10:48 UTC
Labels: duplicate
