### ISSUE TITLE
Feature Request: Allow App to be Exited

### ISSUE THREAD

**Issue by tomcarlson** [meshtastic/Meshtastic-Android#422] opened 2022-04-26 02:35 UTC
I personally do not like that it is impossible for me to stop the Meshtastic App without using Android to  "Force Stop" it.  It probably is not hurting anything for it to be always running, but I have enough OCD that it bugs me not be be able to make the app actually quit running.

Orbot (Tor App) is an example of an app that likes to stay running in the background, but it has a menu option that allows you to exit it.  I wonder if the same scheme could be added to Meshtastic.

**Comment by mc-hamster** [comment] 2022-04-26 03:15
Closed.

Duplicate of: https://github.com/meshtastic/Meshtastic-Android/issues/186

**Closed by mc-hamster** 2022-04-26 03:15 UTC

**Comment by andrekir** [comment] 2022-04-26 13:00
@tomcarlson the app can be gracefully closed when no interfaces are open, ie. "None (disable)" selected on the Settings tab.
