### ISSUE TITLE
Closing app and service

### ISSUE THREAD

**Issue by jacky4566** [meshtastic/Meshtastic-Android#303] opened 2021-11-06 03:44 UTC
Is there a way to kill the app service without going through the setting panel? Seems weird we don't have an "exit" button in the app to kill the service. 

It would also be nice if `android:stopWithTask="true"` was set so when you "close" the app from the task manager it destroys the service.

**Comment by andrekir** [comment] 2022-02-04 18:23
Duplicate of #186

**Closed by andrekir** 2022-02-04 18:23 UTC
