### ISSUE TITLE
Clicking a nodes location take you out of the app.

### ISSUE THREAD

**Issue by SurfingSpider** [meshtastic/Meshtastic-Android#948] opened 2024-04-01 23:18 UTC
Clicking a nodes location take you out of the app.

I can see a reason that might useful to navigate to a node in android another app (e.g. Google maps). But I find myself clicking a nodes location to find out where it is going outside the meshtastic app then going back in. 

As we have the map in the app would it not make more sense take you to that node location inside the map tab in the meshtastic app?

**Comment by andrekir** [comment] 2024-04-02 02:08
Duplicate of #543

**Closed by andrekir** 2024-04-02 02:08 UTC
