### ISSUE TITLE
MQTT Client mode

### ISSUE THREAD

**Issue by tb0hdan** [meshtastic/Meshtastic-Android#612] opened 2023-04-04 05:47 UTC
Hi,

Larger networks that span across cities already run MQTT anyway. Having this will allow communication with everyone on
the network.

Meshtastic Android app already supports TCP/IP for devices, please add MQTT client mode that will allow Internet-only chat.

**Comment by andrekir** [comment] 2023-04-04 08:37
Duplicate of #361

**Closed by andrekir** 2023-04-04 08:37 UTC
