### ISSUE TITLE
[Bug]: Node names displaying incorrectly 

### ISSUE THREAD

**Issue by Gremlin1987** [meshtastic/Meshtastic-Android#1280] opened 2024-10-02 19:39 UTC
### Contact Details

collin87@gmail.com

### What happened?

I have seen several instances where the node name displayed doesn't correspond to the node you're messaging and visa versa.

In the below example I tried to send a message from my mobile node to my Stationary node(Collin's Rak). After sending two messages I got a response which was unexpected. When I backed out of the app and went back into my messages my DM chat renamed from Collin's Rak to Silver Star - West. I found out after a few messages that I wasn't actually messaging silver star west either. I closed the app again and when I re-opened it the chat name changed again with the short name showing up properly but the long name not populating properly.

I had this happen previously in the long fast channel with people showing up under the wrong short name but I did a node DB reset and figured it may have fixed it.

Unfortunately I don't know exact steps to reproduce. It's an issue that just shows up from time to time.

![Screenshot_20241002_095204_Meshtastic](https://github.com/user-attachments/assets/534501b5-3b5e-43f8-8950-9407d4c6c08f)
![Screenshot_20241002_101745_Meshtastic](https://github.com/user-attachments/assets/204bbaa9-bc5c-40ae-b742-7c08e6fe4239)
![Screenshot_20241002_101823_Meshtastic](https://github.com/user-attachments/assets/1870816c-94c4-4a82-a676-bcbe13ce2d71)

### App Version

2.4.4

### Phone

Samsung s24 ultra running Android 14

### Device

Heltec T114 most recently but have experienced it on a Heltec V3 and RAK 26431 as well.

### Firmware

2.4.2.5b45303

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment] 2024-10-02 21:32
this is a known issue, see _https://github.com/meshtastic/Meshtastic-Android/issues/1220#issuecomment-2323430667_

Duplicate of #1220

**Closed by andrekir** 2024-10-02 21:32 UTC
Labels: bug
