### ISSUE TITLE
Channel Setup Blank

### ISSUE THREAD

**Issue by EmileSpecs** [meshtastic/Meshtastic-Android#495] opened 2022-10-11 20:14 UTC
Hi, I have latest Android app (1.2.67) and firmware (1.3.41.80ddb81-d) on T-Beams.

I've done the setup of the T-Beams using the web client.
In the web client I have setup a channel on channel 1.

In the Android app, it seems like the config isn't pulled into the app, the channel page is simply blank.

![Screenshot_20221011-220823_Meshtastic](https://user-images.githubusercontent.com/7687212/195189061-15529b68-e549-43f0-93d5-f7023d9df27e.jpg)

I also had quite a bit of trouble pairing phone to T-Beam after setup on the web client.
So it seems like something isn't quite right.

Anything else I can send to make troubleshooting this easier?

**Comment by andrekir** [comment] 2022-10-11 20:21
https://github.com/meshtastic/Meshtastic-Android/issues/487#issuecomment-1264009306
https://meshtastic.discourse.group/t/meshtastic-device-1-3-42-alpha-release/6561/3

Duplicate of #487

**Closed by andrekir** 2022-10-11 20:21 UTC
