### ISSUE TITLE
[Feature request] Mute chat

### ISSUE THREAD

**Issue by tick-hack** [meshtastic/Meshtastic-Android#868] opened 2024-02-22 21:44 UTC
Guys, please add feature to mute main chat in app, but dont mute personal messages

**Comment by nagumii** [comment] 2024-02-22 22:39
This is a good idea.

Control could be added for different notification categories, as android allows for muting of notifications by type.

Also, the ability to mute a specific channel or node would be great!

**Comment by andrekir** [comment] 2024-02-23 08:43
Duplicate of #511

**Closed by andrekir** 2024-02-23 08:43 UTC
