### ISSUE TITLE
GPS History in Android App 

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1336] opened 2024-10-20 19:26 UTC
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

I'd like the app to have a GPS History in Android App like already in iOS 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment] 2024-10-21 09:03
Duplicate of #550

**Closed by andrekir** 2024-10-21 09:03 UTC
Labels: duplicate

**Comment by cracky22** [comment] 2024-10-21 14:12
How long does it take until the feature arrives?
