### ISSUE TITLE
GPS accuracy circle and date time stamp on map

### ISSUE THREAD

**Issue by DylanHoen** [meshtastic/Meshtastic-Android#183] opened 2020-09-23 20:47 UTC
One of my T-Beams, with likely the latest or second latest firmware and android app (September 20'th, maybe), appeared on the map 100km away, while they were all within 10 meters of me.  That GPS coordinate should have come with some kind of confidence circle and an accurate time stamp.
There is a list of different circles here:
https://en.wikipedia.org/wiki/Circular_error_probable
It seems that there could be a radius of 50% probability, but if you double it, it becomes 95% probability.  The 95% might be the circle I want to see on the map.
Each person could be drawn on the map with a shaded circle of confidence drawn around them.  Each shaded circle of confidence could get darker where they overlap (if that helps distinguish who it belongs to).
Each name on the map should have the timestamp (including date) of the GPS reading, or a measure of how long ago the the GPS reading was made, on the line below the name.
When the GPS coordinates are relayed in, through multiple mesh paths, the time stamps should be used to keep the latest one, and maybe a second coordinate, which is the latest coordinate that's confidence was within a certain radius, like 10 meters.  If the latest measurement is less accurate than the 10 meter accuracy measurement, Both coordinates could be drawn on the map, with the older one being greyed out.  Measurements that are older than an hour ago, or a day ago could be greyed out fainter and fainter.

**Comment by mc-hamster** [comment] 2021-03-27 05:54
Closing this as a duplicate of #392

**Closed by mc-hamster** 2021-03-27 05:54 UTC
