### ISSUE TITLE
Landscape view for map & other screens

### ISSUE THREAD

**Issue by artiommocrenco** [meshtastic/Meshtastic-Android#729] opened 2023-09-13 20:14 UTC
Hi, I'm really missing out landscape view for the Android app.

Is it supported at this point or are there any plans to implement it?

Cheers

**Comment by andrekir** [comment] 2023-09-16 11:43
Duplicate of #159

**Closed by andrekir** 2023-09-16 11:43 UTC

**Comment by artiommocrenco** [comment] 2023-09-16 11:45
I'm buying iPhone then
