### ISSUE TITLE
Traceroutes still fail to register on 2.2.24 app with mixed 2.3.2 and 2.2.23/24 nodes on the mesh.

### ISSUE THREAD

**Issue by eldoctorcool** [meshtastic/Meshtastic-Android#933] opened 2024-03-25 02:10 UTC
I am able to ping 2.3.2 fw and 2.2.23/24 fw nodes from a 2.2.24 fw/app combo, but I am unable to ping a 2.3.2 fw from another 2.3.2 fw, no matter what, when using Android app 2.2.24 paired to a 2.3.2 fw node.

I can't use 2.3.1 Android app b/c the node formatting renders it useless... so I haven't tried with app 2.3.1...

Setup to repro:

x1 RAK4631 on 2.3.2 --> CLIENT
x2 RAK4631 one is on 2.2.23 and another in 2.2.24) --> CLIENT

x1 LoRa32 1_6 on 2.3.2   --> CLIENT
x1 LoRa32 1_6 on 2.2.23  --> ROUTER_CLIENT

Launch 2,2.24 app and pair to the 2.2.23 ROUTER_CLIENT, then Traceroute any node, 2.2.23/24/2.3.2, etc, 100% success. 
Launch 2.2.24 app and pair to one of the two 2.3.2 CLIENT nodes, then Traceroute the other 2.3.2 node, 100% FAIL.

**Comment by b8b8** [comment] 2024-03-25 02:43
is it really an issue if the newer app solves the problem?

**Comment by eldoctorcool** [comment] 2024-03-25 03:23
Simple answer: No. There are zero reasons as to why when a mesh has 2.2.23/2.2.24 nodes mixed with 2.3.2 nodes should fail to Traceroute, regardless of fw/app combo used. That is unless it was stated by the Meshtastic release notes that the new fw version will be breaking backwards compat, which it hasn't been stated AFAIK.

**Comment by GUVWAF** [comment] 2024-03-25 06:54
I can't reproduce this. Traceroutes between nodes on 2.3.2 using the Android app works fine for me.

Make sure you have identical channel settings on both devices.

**Comment by eldoctorcool** [comment] 2024-03-25 07:06
Do we know why the popup is not showing on 2.2.23/2.2.24 app?

**Comment by eldoctorcool** [comment] 2024-03-25 07:16
In regards to Android app v2.3.0, that is non-usable in our devices due to formatting issues on the node screen... (which I reported on another bug...) so updating to the v2.3.x app it will be just trading one issue for another... and right now, having a functional app comes before having traceroutes... and therefore, we've been holding off on the mesh update to 2.3.x... until all these teething issues are resolved. Thanks.

**Comment by eureekasigns** [comment] 2024-03-26 00:25
Just to add another note, the traces also show a direct hop with other, older nodes in the middle. From location where it needs at least one other node to make the connection, the trace shows only the destination node with 2.3.2 firmware.

App 2.3.1 and 2 RAK4631nodes with 2.3.2.

**Comment by eldoctorcool** [comment] 2024-03-26 23:41
I've already tried the smallest font size on these devices, screen size, etc, unfortunately it didn't work. These devices worked fine with everything since 2.0, With that said, there is something the 2.3.x fw is doing differently when it receives a Traceroute packet that the app 2.2.24 isn't picking it up when there are 2 or more 2.3.x nodes in the mesh. So, that sounds like there might be a FW issue there.

Since you can repro the issue I am having, what would be different in the traceroute packet received by the node vs. a 2.2.xx mesh.

Thanks.

**Comment by GUVWAF** [comment] 2024-03-27 07:51
> Since you can repro the issue I am having, what would be different in the traceroute packet received by the node vs. a 2.2.xx mesh.

Nothing special for traceroute, an additional field `hopStart` was added to each MeshPacket, but that should be backwards compatible. Somebody else noticed the admin channel also doesn't work with app version 2.2.24 with 2.3.2 firmware, maybe @andrekir might know why that is the case. 

That said, it's fixed by using the Android app version >=2.3.0, and updating the app is really the best solution here.

**Comment by eldoctorcool** [comment] 2024-03-27 08:57
I understand, unfortunately, until the formatting bug is fixed I can't move to the 2.3.x app. 

Tracerouting to a 2.3.2 node works from a 2.2.24 app so long it is the only 2.3.x node in the mesh. Once you add a 2nd node with 2.3.x, then traceroutes stop working. That looks like a bug.

As for the admin channel with 2.2.24 app to a 2.3.2 node... I just quickly tested that and it seems to work for me (2.2.24 app managing a remote 2.3.2 fw node)

**Comment by GUVWAF** [comment] 2024-03-27 09:04
> Once you add a 2nd node with 2.3.x, then traceroutes stop working. That looks like a bug.

Are you using 2.3.0 or 2.3.1? Those firmware versions are revoked and should not be used, only 2.3.2 is stable.

**Closed** 2024-04-28 11:10 UTC
