### ISSUE TITLE
[Feature Request]: traceroute color

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1472] opened 2024-12-15 00:44 UTC
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

The traceroute nodes in the color of their color to see on the traceroute 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment] 2024-12-17 15:37
Duplicate of #1207

**Closed by andrekir** 2024-12-17 15:37 UTC
Labels: enhancement
