### ISSUE TITLE
Samsung S5 (SM-G900F) Android 6.0.1

### ISSUE THREAD

**Issue by slavino** [meshtastic/Meshtastic-Android#80] opened 2020-07-02 12:18 UTC
![Screenshot_2020-07-02-13-51-49](https://user-images.githubusercontent.com/1584034/86356959-6fb7e000-bc6d-11ea-8a45-f8eae4208445.png)

Device fails to display QR code and channel name

**Comment by geeksville** [comment] 2020-07-02 15:16
interesting!  It looks like it might screen size scaling issue.  Otherwise the device basically works okay?  I can make a similar screen in the android sim and try to reproduce.

**Comment by geeksville** [comment] 2020-07-02 16:42
hmm - no the screen scaling is not a problem, I just tried it in sim with a bunch of screen sizes.  hmm.

**Comment by geeksville** [comment] 2020-07-02 16:47
hmm - the problem is that channel is null (when it should not be).  To help me figure this out can you do two things:

* Does the channel QRcode show up while the device is connected?
* After the channel is not showing can you click "report bug" in the app and then make a note here? and I'll go look at the logs.

**Comment by slavino** [comment] 2020-07-03 08:26
Let's check once I have my boards T-Beam_v0.7 flashed with production build from GITHUB releases.

Could be really only some constellation of TBeam_v1.x firmware on TBeam_v0.7 hardware. Power management behavior differs quite a lot between these two as on older board is AXP202X missing...

**Comment by geeksville** [comment] 2020-09-16 17:34
I fixed some screen scaling.  I think this is fixed now.  If not, would you mind reopening?

**Closed by geeksville** 2020-09-16 17:34 UTC
Labels: bug
