### ISSUE TITLE
Feature Request: Ability to send & receive messages to MQTT-server from App

### ISSUE THREAD

**Issue by djjayballz** [meshtastic/Meshtastic-Android#512] opened 2022-11-01 20:42 UTC
Hi,
i thought it would be nice to be able to send and receive messages from a MQTT server right out the app.
So one can send and receive messages without having a LoRa deveice coupled. Maybe for cases when the battery is low

What do you think?

**Comment by andrekir** [comment] 2022-11-02 01:05
Duplicate of #361

**Closed by andrekir** 2022-11-02 01:05 UTC
