### ISSUE TITLE
Owner/name can't be changed

### ISSUE THREAD

**Issue by tropho23** [meshtastic/Meshtastic-Android#320] opened 2021-12-10 14:18 UTC
v1.2.50 alpha reintroduced the issue fixed by v1.2.45 beta where "Your name" (node name) field does not allow confirmation, and thus reverts to the last name and does not save the change.  v1.2.45 seemed to fix this, offering the user a check mark key on the onscreen Android keyboard, and v1.2.50 reverts to the pre-1.2.45 issue where only an enter key is present on the onscreen keyboard, preventing confirmation of what was entered into the "Your name" field.

If I uninstall v1.2.50 alpha and reinstall v1.2.45 beta, the issue is fixed, and changes to the "Your name" field can be confirmed and accepted.

I have reproduced this issue with v1.2.50 alpha on these devices:
- Samsung Galaxy S10e phone running Android 11
- Samsung Galaxy Tab A 10.1 tablet running Android 8.1
- Walmart Onn 10.1 tablet running Android 9

**Comment by andrekir** [comment] 2021-12-10 14:34
Duplicate of #311

**Closed by andrekir** 2021-12-10 14:34 UTC
