### ISSUE TITLE
[Feature Request]: UI works without a radio

### ISSUE THREAD

**Issue by pmarches** [meshtastic/Meshtastic-Android#758] opened 2023-10-08 19:11 UTC
I would like my internet connected but radio-less users to send their messages thru MQTT over their phone internet connection (Wifi/LTE). Since I have a node that has good LoRa reception **and** starlink connectivity, that node will act as a bridge/repeater. 

Thus, my internet-only users can make use of the chat and location features even if they do not have direct LoRa access.

**Comment by Ferretdog** [comment] 2024-01-12 22:13
This would seem to create a spam danger which would need guarding against. Right now that danger is limited by the step of buying the hardware.

**Comment by andrekir** [comment] 2024-06-08 10:35
Duplicate of #361

**Closed by andrekir** 2024-06-08 10:35 UTC
