### ISSUE TITLE
[Feature Request] Manually specify the IP address of the node to link to (phone app)

### ISSUE THREAD

**Issue by MihaiRF** [meshtastic/Meshtastic-Android#503] opened 2022-10-26 16:32 UTC
Hi,
It would be very nice to be able to connect to a specific IP address when linking a Wi-fi activated device, not only the ones being discovered automatically in the same netmask (when taping the "+" sign).
At the moment, (1.3.45) the IPs are present for a while in the app, but they tend to disappear if not used.
The use case is for remote accessing the nodes (through VPN sub-nets, or generally routed IPs that are not within the same network mask)

Thank you!

**Comment by andrekir** [comment] 2022-10-26 19:04
Duplicate of #472

**Closed by andrekir** 2022-10-26 19:04 UTC
