### ISSUE TITLE
[Feature Request]: Sort/Filter Nodes

### ISSUE THREAD

**Issue by ghsni** [meshtastic/Meshtastic-Android#849] opened 2024-02-13 02:42 UTC
- Sorting or filtering nodes in the nodes page can be helpful to those who wish to filter out MQTT Nodes and only display nodes that are local to them. Shouts to MKJN for helping me think of this.

- Filtering out attribute data fields for nodes not associated to the main meshtastic account could be helpful too (seeing an RSSI, SNR or Atmospheric Pressure readings in Southern California is not much help to someone living in Nebraska or Maine)

**Comment by andrekir** [comment] 2024-02-13 08:41
Duplicate of #824 #249

**Closed by andrekir** 2024-02-13 08:41 UTC
