### ISSUE TITLE
[Bug]: IAQ shown on the graph for BME280 sensor instead of Barometric pressure. 

### ISSUE THREAD

**Issue by Synthacon** [meshtastic/Meshtastic-Android#1440] opened 2024-11-28 08:47 UTC
### What happened?

In "Environmental Metrics Log" IAQ is shown on the graph even if no BME680 sensor is connected. 

Instead of showing this totally useless NULL information it should be possible to plot Barometric pressure that BME280 measures. 

### App Version

2.5.10

### Phone

OP8PRO

### Device

LilyGO LoRa32 1.6.1

### Firmware

2.5.11.8e2a3e5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment] 2024-11-28 11:01
Duplicate of #1325

**Closed by andrekir** 2024-11-28 11:01 UTC
Labels: bug
